# Generated by Django 5.2.11 on 2026-02-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_betainvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='final_video_gcs_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='final_video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
